### ISSUE TITLE
Error creating an existing polygon in symmetry mode

### ISSUE THREAD

**Issue by jeissonlazo** [Dangry98/PolyQuilt-for-Blender-4.0#11]
**step one** 
modify without having symmetry activated
![step1](https://github.com/user-attachments/assets/971e78f5-4f8f-43fc-babc-b2b08f9e55b5)
**step two** 
Activate symmetry and make a polygon that already exists on one of the sides
![step2](https://github.com/user-attachments/assets/fb5165db-b08e-4c02-9619-17f5b821c6db)
step three
create the polygon in symmetry
![step3](https://github.com/user-attachments/assets/4a5eec0a-8236-4cc4-a313-b17d526f2834)

`Python: Traceback (most recent call last):
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\pq_operator.py", line 197, in modal
    raise e
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\pq_operator.py", line 193, in modal
    val = self.update( context, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\pq_operator.py", line 231, in update
    ret = self.currentSubTool.Update(context, event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\subtools\subtool.py", line 105, in Update
    ret = self.OnUpdate(context,event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\subtools\subtool.py", line 243, in OnUpdate
    return self.LMBEvent.Update(context,event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\utils\mouse_event_util.py", line 96, in Update
    ret = self.Execute( context , event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\utils\mouse_event_util.py", line 126, in Execute
    result = self.OnEvent( event , MBEventType.Click , result )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\utils\mouse_event_util.py", line 174, in OnEvent
    ret = self.eventFunc( self)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\subtools\maintool_brush.py", line 61, in LMBEventCallback
    tools = [ t( event.event , self) for t in self.callback[event.type] if t.Check( self , self.currentTarget ) ]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\subtools\maintool_brush.py", line 61, in <listcomp>
    tools = [ t( event.event , self) for t in self.callback[event.type] if t.Check( self , self.currentTarget ) ]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\subtools\subtool_autoquad.py", line 54, in __init__
    face = self.bmo.AddFace(vs, normal)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\QMesh\QMeshOperators.py", line 271, in AddFace
    face_mirror = self.AddFace( mirror , normal , False )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeiss\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\PolyQuilt_Fork\QMesh\QMeshOperators.py", line 238, in AddFace
    face = self.bm.faces.new( verts )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: faces.new(verts): face already exists
`

**Comment by Dangry98** [comment]
Hi @jeissonlazo, thanks for the report. I think this issue is already kown, but last time I was unable to fix it. I do another attempt soon :)
