### ISSUE TITLE
4.1 Error activating the Addon Version 1.3.1

### ISSUE THREAD

**Issue by TCFrancis** [Dangry98/PolyQuilt-for-Blender-4.0#4]
During Addon activation I get the following Error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\PolyQuilt\__init__.py", line 28, in <module>
    from .pq_operator import *
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\PolyQuilt\pq_operator.py", line 27, in <module>
    from .utils import draw_util
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\PolyQuilt\utils\__init__.py", line 24, in <module>
    from . import mouse_event_util
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\PolyQuilt\utils\mouse_event_util.py", line 20, in <module>
    from . import draw_util
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\PolyQuilt\utils\draw_util.py", line 68, in <module>
    shader2D = gpu.shader.from_builtin("2D_UNIFORM_COLOR")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'

Another User with the same error: https://blenderartists.org/t/polyquilt-addon-for-blender-2-8/1168918/632

**Comment by designerontherun** [comment]
You have to download Dangry's forked version 1.5.2. Sakana hasn't updated his version for quite some time so version 1.3.1 isn't supported in 4.1.
